ALTER TABLE users
ADD COLUMN password VARCHAR(255) NOT NULL DEFAULT 'TEMP',
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;